### ISSUE TITLE
Automatically sync emojis list

### ISSUE THREAD

**Issue by gustavopch** [arvinxx/commitlint-config-gitmoji#5]
Hey, this lib becomes out of sync whenever gitmoji adds a new emoji. Here's how I managed to solve the problem.

- Add gitmoji to the dev dependencies. Unfortunately gitmoji is not available from NPM, so we must point to the GitHub repo.
```json
    "gitmoji": "carloscuesta/gitmoji",
```

- Change the commitlint config file:
```js
const { gitmojis } = require('gitmoji/src/data/gitmojis.json')
const allGitmojiCodes = gitmojis.map(gitmoji => gitmoji.code)

module.exports = {
  rules: {
    'type-enum': [2, 'always', allGitmojiCodes],
```

What do you think? Would you like a PR?

**Comment by gustavopch** [comment]
Downside of the approach above is that it will install all dependencies from the gitmoji repository. Almost doubled the contents of my yarn.lock file :fearful:.

I have another idea. We can download the gitmojis.json file from GitHub and place it in `os.tmpdir()`. Next time, if the file already exists, skip the download.

```js
const downloadSync = (url, targetPath) => {
  const result = require('child_process').execFileSync('curl', ['--silent', '-L', url], {
    encoding: 'utf8',
    maxBuffer: Infinity,
  })

  fs.writeFileSync(targetPath, result)
}

const filePath = join(os.tmpdir(), 'gitmojis.json')

// Download gitmoji.json if not already downloaded
if (!fs.existsSync(filePath)) {
  downloadSync('https://raw.githubusercontent.com/carloscuesta/gitmoji/master/src/data/gitmojis.json', filePath)
}

const { gitmojis } = require(filePath)
const allGitmojiCodes = gitmojis.map(gitmoji => gitmoji.code)

module.exports = {
  rules: {
    'type-enum': [2, 'always', allGitmojiCodes],
```

Now in order to update the list of emojis the user only needs to `rm /tmp/gitmojis.json` (so that it'll be downloaded again next time commitlint runs). Or maybe we should keep the file at `join(__dirname, 'gitmojis.json') // => "node_modules/commitlint-config-gitmoji/gitmojis.json"` so that deleting the node_modules folder will also delete it (which seems to be what users would expect).

**Comment by khaosdoctor** [comment]
The second approach is better in my opinion

**Comment by gustavopch** [comment]
@khaosdoctor Thanks for the comment.

What do you think about **a)** saving to `/tmp/gitmojis.json` Vs. **b)** saving to `node_modules/commitlint-config-gitmoji/gitmojis.json`?
